import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { BsMoonStarsFill } from "react-icons/bs";
import { useDispatch, useSelector } from "react-redux";
import { ToastContainer } from "react-toastify";
import { toggleDarkMode } from "../utils/mainReducer";
import { useSession } from "next-auth/react";
import 'react-toastify/dist/ReactToastify.css'

export default function Layout({ children, title }) {
  const { status, data: session } = useSession();

  const { darkMode, cart } = useSelector((state) => state.main);
  const dispatch = useDispatch();
  const [cartCount, setCartCount] = useState(0);

  useEffect(() => {
    setCartCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, []);

  return (
    <>
      <Head>
        <title>{title ? title + " - eCommerce" : "eCommerce"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position="bottom-center" limit={1} />
      <div
        className={`flex min-h-screen flex-col justify-between ${
          darkMode ? "dark bg-dark-back" : ""
        }`}
      >
        <header>
          <nav className="flex h-16 justify-between bg-emerald-400 px-5 items-center shadow-md">
            <Link className="text-2xl font-bold" href="/">
              eCommerce
            </Link>
            <div className="flex gap-5 p-2 text-lg">
              <BsMoonStarsFill
                size={30}
                onClick={() => dispatch(toggleDarkMode())}
              />
              <Link href="/cart">
                Cart
                {cartCount > 0 && (
                  <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                    {cart.cartItems.reduce((a, c) => a + c.quantity, 0)}
                  </span>
                )}
              </Link>
              {status === "loading" ? (
                "loading"
              ) : session?.user ? (
                session.user.name
              ) : (
                <Link href="/login">Login</Link>
              )}
            </div>
          </nav>
        </header>
        <main className={`container m-auto mt-10 px-4`}>{children}</main>
        <footer className="flex justify-center items-center h-10 bg-emerald-800 text-white">
          Copyright &copy; {new Date().getFullYear()} eCommerce{" "}
        </footer>
      </div>
    </>
  );
}
