import React from "react";
import Head from "next/head";
import Link from "next/link";

export default function Layout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title ? title + " - eCommerce" : "eCommerce"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
            <nav className="flex h-16 justify-between bg-emerald-400 px-5 items-center shadow-md">
                <Link className="text-2xl font-bold" href="/">
                   eCommerce
                </Link>
                <div className="flex gap-5 p-2 text-lg">
                    <Link href="/cart">Cart</Link>
                    <Link href="/login">Login</Link>
                </div>
            </nav>
        </header>
        <main className="container m-auto mt-10 px-4">{children}</main>
        <footer className="flex justify-center items-center h-10 bg-emerald-800 text-white">Copyright &copy; {new Date().getFullYear()} eCommerce </footer>
      </div>
    </>
  );
}
